[features]
seeds = false
skip-lint = false

[programs.localnet]
futstar_momentum_trading = "FuTsTar11111111111111111111111111111111111"

[programs.devnet]
futstar_momentum_trading = "FuTsTar11111111111111111111111111111111111"

[programs.mainnet]
futstar_momentum_trading = "FuTsTar11111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "11111111111111111111111111111111"
program = "./target/deploy/futstar_momentum_trading.so"

[workspace]
members = ["programs/momentum-trading"]

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"
